### ISSUE TITLE
Latest Octoprint support (>1.3.1 or 1.4.0)

### ISSUE THREAD

**Issue by asys3** [AmedeeBulle/octoprint-containers#5]
The release-tag changed in Octoprint. So there's no LATEST tag anymore. 
The result ist that docker-compose build will no longer work.
As seen here:
[octoprintLatestBuildError.txt](https://github.com/AmedeeBulle/octoprint-containers/files/4512066/octoprintLatestBuildError.txt)

When pinning to an explicit version in docker-compose the compile/build fails.
Seems to have to do with the new python version used in Octoprint.
[octoprintPythonError.txt](https://github.com/AmedeeBulle/octoprint-containers/files/4512065/octoprintPythonError.txt)

Hope to get this fixed, because this is a nice project.

Thanks,
Uwe

**Comment by AmedeeBulle** [comment]
Hi!

It took me sometime to figure out the issue...

The issue is that Jinja requires a recent version of MarkupSafe, and latest 2.0 fails.
Pre-installing MarkupSafe solves the issue.

After the facts, I found: https://github.com/OctoPrint/OctoPrint/commit/4ddaf350b4dd03c0bfa2bb6bc39ef49ac99e6d34 which means it is solved in OctoPrint, but not released yet.
